insert into cidade (idCidade, nome, uf) values (1, 'Longview', 'TX');
insert into cidade (idCidade, nome, uf) values (2, 'Indianapolis', 'IN');
insert into cidade (idCidade, nome, uf) values (3, 'Dallas', 'TX');
insert into cidade (idCidade, nome, uf) values (4, 'Gainesville', 'FL');
insert into cidade (idCidade, nome, uf) values (5, 'Fullerton', 'CA');
insert into cidade (idCidade, nome, uf) values (6, 'Greensboro', 'NC');
insert into cidade (idCidade, nome, uf) values (7, 'Columbia', 'SC');
insert into cidade (idCidade, nome, uf) values (8, 'New Orleans', 'LA');
insert into cidade (idCidade, nome, uf) values (9, 'Rochester', 'NY');
insert into cidade (idCidade, nome, uf) values (10, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (11, 'Long Beach', 'CA');
insert into cidade (idCidade, nome, uf) values (12, 'Gainesville', 'FL');
insert into cidade (idCidade, nome, uf) values (13, 'Gilbert', 'AZ');
insert into cidade (idCidade, nome, uf) values (14, 'Scottsdale', 'AZ');
insert into cidade (idCidade, nome, uf) values (15, 'Peoria', 'IL');
insert into cidade (idCidade, nome, uf) values (16, 'New York City', 'NY');
insert into cidade (idCidade, nome, uf) values (17, 'Ridgely', 'MD');
insert into cidade (idCidade, nome, uf) values (18, 'Peoria', 'IL');
insert into cidade (idCidade, nome, uf) values (19, 'Jersey City', 'NJ');
insert into cidade (idCidade, nome, uf) values (20, 'Peoria', 'IL');
insert into cidade (idCidade, nome, uf) values (21, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (22, 'Fort Myers', 'FL');
insert into cidade (idCidade, nome, uf) values (23, 'Omaha', 'NE');
insert into cidade (idCidade, nome, uf) values (24, 'Lansing', 'MI');
insert into cidade (idCidade, nome, uf) values (25, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (26, 'Nashville', 'TN');
insert into cidade (idCidade, nome, uf) values (27, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (28, 'Cheyenne', 'WY');
insert into cidade (idCidade, nome, uf) values (29, 'Jacksonville', 'FL');
insert into cidade (idCidade, nome, uf) values (30, 'Torrance', 'CA');
insert into cidade (idCidade, nome, uf) values (31, 'Buffalo', 'NY');
insert into cidade (idCidade, nome, uf) values (32, 'Cincinnati', 'OH');
insert into cidade (idCidade, nome, uf) values (33, 'Lake Charles', 'LA');
insert into cidade (idCidade, nome, uf) values (34, 'New Brunswick', 'NJ');
insert into cidade (idCidade, nome, uf) values (35, 'Lansing', 'MI');
insert into cidade (idCidade, nome, uf) values (36, 'Green Bay', 'WI');
insert into cidade (idCidade, nome, uf) values (37, 'San Antonio', 'TX');
insert into cidade (idCidade, nome, uf) values (38, 'Saint Louis', 'MO');
insert into cidade (idCidade, nome, uf) values (39, 'Charleston', 'WV');
insert into cidade (idCidade, nome, uf) values (40, 'San Antonio', 'TX');
insert into cidade (idCidade, nome, uf) values (41, 'Charlotte', 'NC');
insert into cidade (idCidade, nome, uf) values (42, 'Phoenix', 'AZ');
insert into cidade (idCidade, nome, uf) values (43, 'Albany', 'NY');
insert into cidade (idCidade, nome, uf) values (44, 'Lafayette', 'LA');
insert into cidade (idCidade, nome, uf) values (45, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (46, 'Saint Petersburg', 'FL');
insert into cidade (idCidade, nome, uf) values (47, 'Erie', 'PA');
insert into cidade (idCidade, nome, uf) values (48, 'Cleveland', 'OH');
insert into cidade (idCidade, nome, uf) values (49, 'Kansas City', 'MO');
insert into cidade (idCidade, nome, uf) values (50, 'Salt Lake City', 'UT');
insert into cidade (idCidade, nome, uf) values (51, 'Denver', 'CO');
insert into cidade (idCidade, nome, uf) values (52, 'Lexington', 'KY');
insert into cidade (idCidade, nome, uf) values (53, 'Las Vegas', 'NV');
insert into cidade (idCidade, nome, uf) values (54, 'Baton Rouge', 'LA');
insert into cidade (idCidade, nome, uf) values (55, 'Portland', 'OR');
insert into cidade (idCidade, nome, uf) values (56, 'San Antonio', 'TX');
insert into cidade (idCidade, nome, uf) values (57, 'Las Vegas', 'NV');
insert into cidade (idCidade, nome, uf) values (58, 'Humble', 'TX');
insert into cidade (idCidade, nome, uf) values (59, 'Wilkes Barre', 'PA');
insert into cidade (idCidade, nome, uf) values (60, 'Chicago', 'IL');
insert into cidade (idCidade, nome, uf) values (61, 'Louisville', 'KY');
insert into cidade (idCidade, nome, uf) values (62, 'Houston', 'TX');
insert into cidade (idCidade, nome, uf) values (63, 'Cleveland', 'OH');
insert into cidade (idCidade, nome, uf) values (64, 'Lincoln', 'NE');
insert into cidade (idCidade, nome, uf) values (65, 'Corona', 'CA');
insert into cidade (idCidade, nome, uf) values (66, 'Houston', 'TX');
insert into cidade (idCidade, nome, uf) values (67, 'Corpus Christi', 'TX');
insert into cidade (idCidade, nome, uf) values (68, 'Fort Worth', 'TX');
insert into cidade (idCidade, nome, uf) values (69, 'Dallas', 'TX');
insert into cidade (idCidade, nome, uf) values (70, 'Wilmington', 'NC');
insert into cidade (idCidade, nome, uf) values (71, 'Fort Worth', 'TX');
insert into cidade (idCidade, nome, uf) values (72, 'Gaithersburg', 'MD');
insert into cidade (idCidade, nome, uf) values (73, 'Gainesville', 'FL');
insert into cidade (idCidade, nome, uf) values (74, 'Corona', 'CA');
insert into cidade (idCidade, nome, uf) values (75, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (76, 'Jacksonville', 'FL');
insert into cidade (idCidade, nome, uf) values (77, 'Spring Hill', 'FL');
insert into cidade (idCidade, nome, uf) values (78, 'Ogden', 'UT');
insert into cidade (idCidade, nome, uf) values (79, 'San Diego', 'CA');
insert into cidade (idCidade, nome, uf) values (80, 'Stamford', 'CT');
insert into cidade (idCidade, nome, uf) values (81, 'Indianapolis', 'IN');
insert into cidade (idCidade, nome, uf) values (82, 'Visalia', 'CA');
insert into cidade (idCidade, nome, uf) values (83, 'Atlanta', 'GA');
insert into cidade (idCidade, nome, uf) values (84, 'Dallas', 'TX');
insert into cidade (idCidade, nome, uf) values (85, 'Tampa', 'FL');
insert into cidade (idCidade, nome, uf) values (86, 'Evansville', 'IN');
insert into cidade (idCidade, nome, uf) values (87, 'Ogden', 'UT');
insert into cidade (idCidade, nome, uf) values (88, 'Syracuse', 'NY');
insert into cidade (idCidade, nome, uf) values (89, 'College Station', 'TX');
insert into cidade (idCidade, nome, uf) values (90, 'Saint Paul', 'MN');
insert into cidade (idCidade, nome, uf) values (91, 'Greenville', 'SC');
insert into cidade (idCidade, nome, uf) values (92, 'Richmond', 'VA');
insert into cidade (idCidade, nome, uf) values (93, 'Bakersfield', 'CA');
insert into cidade (idCidade, nome, uf) values (94, 'Charlotte', 'NC');
insert into cidade (idCidade, nome, uf) values (95, 'South Lake Tahoe', 'CA');
insert into cidade (idCidade, nome, uf) values (96, 'Greenville', 'SC');
insert into cidade (idCidade, nome, uf) values (97, 'Frederick', 'MD');
insert into cidade (idCidade, nome, uf) values (98, 'Harrisburg', 'PA');
insert into cidade (idCidade, nome, uf) values (99, 'Cleveland', 'OH');
insert into cidade (idCidade, nome, uf) values (100, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (101, 'Oakland', 'CA');
insert into cidade (idCidade, nome, uf) values (102, 'Charlotte', 'NC');
insert into cidade (idCidade, nome, uf) values (103, 'Cincinnati', 'OH');
insert into cidade (idCidade, nome, uf) values (104, 'Salt Lake City', 'UT');
insert into cidade (idCidade, nome, uf) values (105, 'Miami', 'FL');
insert into cidade (idCidade, nome, uf) values (106, 'Moreno Valley', 'CA');
insert into cidade (idCidade, nome, uf) values (107, 'Albany', 'NY');
insert into cidade (idCidade, nome, uf) values (108, 'Valley Forge', 'PA');
insert into cidade (idCidade, nome, uf) values (109, 'Minneapolis', 'MN');
insert into cidade (idCidade, nome, uf) values (110, 'Los Angeles', 'CA');
insert into cidade (idCidade, nome, uf) values (111, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (112, 'Flint', 'MI');
insert into cidade (idCidade, nome, uf) values (113, 'Harrisburg', 'PA');
insert into cidade (idCidade, nome, uf) values (114, 'Santa Barbara', 'CA');
insert into cidade (idCidade, nome, uf) values (115, 'Houston', 'TX');
insert into cidade (idCidade, nome, uf) values (116, 'Metairie', 'LA');
insert into cidade (idCidade, nome, uf) values (117, 'Phoenix', 'AZ');
insert into cidade (idCidade, nome, uf) values (118, 'Cleveland', 'OH');
insert into cidade (idCidade, nome, uf) values (119, 'Houston', 'TX');
insert into cidade (idCidade, nome, uf) values (120, 'New Brunswick', 'NJ');
insert into cidade (idCidade, nome, uf) values (121, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (122, 'Young America', 'MN');
insert into cidade (idCidade, nome, uf) values (123, 'Sacramento', 'CA');
insert into cidade (idCidade, nome, uf) values (124, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (125, 'Daytona Beach', 'FL');
insert into cidade (idCidade, nome, uf) values (126, 'Northridge', 'CA');
insert into cidade (idCidade, nome, uf) values (127, 'Houston', 'TX');
insert into cidade (idCidade, nome, uf) values (128, 'Knoxville', 'TN');
insert into cidade (idCidade, nome, uf) values (129, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (130, 'Charleston', 'WV');
insert into cidade (idCidade, nome, uf) values (131, 'Schenectady', 'NY');
insert into cidade (idCidade, nome, uf) values (132, 'Whittier', 'CA');
insert into cidade (idCidade, nome, uf) values (133, 'San Francisco', 'CA');
insert into cidade (idCidade, nome, uf) values (134, 'Bethesda', 'MD');
insert into cidade (idCidade, nome, uf) values (135, 'Oklahoma City', 'OK');
insert into cidade (idCidade, nome, uf) values (136, 'Mobile', 'AL');
insert into cidade (idCidade, nome, uf) values (137, 'Dallas', 'TX');
insert into cidade (idCidade, nome, uf) values (138, 'Portland', 'OR');
insert into cidade (idCidade, nome, uf) values (139, 'Minneapolis', 'MN');
insert into cidade (idCidade, nome, uf) values (140, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (141, 'Corpus Christi', 'TX');
insert into cidade (idCidade, nome, uf) values (142, 'Albany', 'NY');
insert into cidade (idCidade, nome, uf) values (143, 'Tulsa', 'OK');
insert into cidade (idCidade, nome, uf) values (144, 'Albuquerque', 'NM');
insert into cidade (idCidade, nome, uf) values (145, 'Fayetteville', 'NC');
insert into cidade (idCidade, nome, uf) values (146, 'Corona', 'CA');
insert into cidade (idCidade, nome, uf) values (147, 'Fresno', 'CA');
insert into cidade (idCidade, nome, uf) values (148, 'Portland', 'OR');
insert into cidade (idCidade, nome, uf) values (149, 'Raleigh', 'NC');
insert into cidade (idCidade, nome, uf) values (150, 'Arlington', 'VA');
insert into cidade (idCidade, nome, uf) values (151, 'Fort Collins', 'CO');
insert into cidade (idCidade, nome, uf) values (152, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (153, 'Austin', 'TX');
insert into cidade (idCidade, nome, uf) values (154, 'San Jose', 'CA');
insert into cidade (idCidade, nome, uf) values (155, 'Buffalo', 'NY');
insert into cidade (idCidade, nome, uf) values (156, 'Tucson', 'AZ');
insert into cidade (idCidade, nome, uf) values (157, 'Bakersfield', 'CA');
insert into cidade (idCidade, nome, uf) values (158, 'Philadelphia', 'PA');
insert into cidade (idCidade, nome, uf) values (159, 'Jamaica', 'NY');
insert into cidade (idCidade, nome, uf) values (160, 'Tulsa', 'OK');
insert into cidade (idCidade, nome, uf) values (161, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (162, 'Shreveport', 'LA');
insert into cidade (idCidade, nome, uf) values (163, 'Largo', 'FL');
insert into cidade (idCidade, nome, uf) values (164, 'San Francisco', 'CA');
insert into cidade (idCidade, nome, uf) values (165, 'Orlando', 'FL');
insert into cidade (idCidade, nome, uf) values (166, 'Syracuse', 'NY');
insert into cidade (idCidade, nome, uf) values (167, 'Salt Lake City', 'UT');
insert into cidade (idCidade, nome, uf) values (168, 'Nashville', 'TN');
insert into cidade (idCidade, nome, uf) values (169, 'Jacksonville', 'FL');
insert into cidade (idCidade, nome, uf) values (170, 'Saint Paul', 'MN');
insert into cidade (idCidade, nome, uf) values (171, 'Buffalo', 'NY');
insert into cidade (idCidade, nome, uf) values (172, 'Odessa', 'TX');
insert into cidade (idCidade, nome, uf) values (173, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (174, 'Vancouver', 'WA');
insert into cidade (idCidade, nome, uf) values (175, 'Bryan', 'TX');
insert into cidade (idCidade, nome, uf) values (176, 'Brooklyn', 'NY');
insert into cidade (idCidade, nome, uf) values (177, 'Fayetteville', 'NC');
insert into cidade (idCidade, nome, uf) values (178, 'Memphis', 'TN');
insert into cidade (idCidade, nome, uf) values (179, 'Cincinnati', 'OH');
insert into cidade (idCidade, nome, uf) values (180, 'Cheyenne', 'WY');
insert into cidade (idCidade, nome, uf) values (181, 'Midland', 'MI');
insert into cidade (idCidade, nome, uf) values (182, 'Pueblo', 'CO');
insert into cidade (idCidade, nome, uf) values (183, 'Augusta', 'GA');
insert into cidade (idCidade, nome, uf) values (184, 'Mesa', 'AZ');
insert into cidade (idCidade, nome, uf) values (185, 'Kansas City', 'MO');
insert into cidade (idCidade, nome, uf) values (186, 'New York City', 'NY');
insert into cidade (idCidade, nome, uf) values (187, 'Philadelphia', 'PA');
insert into cidade (idCidade, nome, uf) values (188, 'Largo', 'FL');
insert into cidade (idCidade, nome, uf) values (189, 'Jackson', 'MS');
insert into cidade (idCidade, nome, uf) values (190, 'Oklahoma City', 'OK');
insert into cidade (idCidade, nome, uf) values (191, 'Tulsa', 'OK');
insert into cidade (idCidade, nome, uf) values (192, 'Peoria', 'IL');
insert into cidade (idCidade, nome, uf) values (193, 'San Diego', 'CA');
insert into cidade (idCidade, nome, uf) values (194, 'Portland', 'OR');
insert into cidade (idCidade, nome, uf) values (195, 'Arlington', 'VA');
insert into cidade (idCidade, nome, uf) values (196, 'Mobile', 'AL');
insert into cidade (idCidade, nome, uf) values (197, 'Billings', 'MT');
insert into cidade (idCidade, nome, uf) values (198, 'Huntington', 'WV');
insert into cidade (idCidade, nome, uf) values (199, 'Charleston', 'SC');
insert into cidade (idCidade, nome, uf) values (200, 'New Orleans', 'LA');
insert into cidade (idCidade, nome, uf) values (201, 'North Hollywood', 'CA');
insert into cidade (idCidade, nome, uf) values (202, 'Clearwater', 'FL');
insert into cidade (idCidade, nome, uf) values (203, 'Boise', 'ID');
insert into cidade (idCidade, nome, uf) values (204, 'Topeka', 'KS');
insert into cidade (idCidade, nome, uf) values (205, 'Norfolk', 'VA');
insert into cidade (idCidade, nome, uf) values (206, 'Fort Lauderdale', 'FL');
insert into cidade (idCidade, nome, uf) values (207, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (208, 'Canton', 'OH');
insert into cidade (idCidade, nome, uf) values (209, 'Athens', 'GA');
insert into cidade (idCidade, nome, uf) values (210, 'Springfield', 'MO');
insert into cidade (idCidade, nome, uf) values (211, 'Columbus', 'GA');
insert into cidade (idCidade, nome, uf) values (212, 'New Haven', 'CT');
insert into cidade (idCidade, nome, uf) values (213, 'Cleveland', 'OH');
insert into cidade (idCidade, nome, uf) values (214, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (215, 'Newark', 'NJ');
insert into cidade (idCidade, nome, uf) values (216, 'Austin', 'TX');
insert into cidade (idCidade, nome, uf) values (217, 'Dallas', 'TX');
insert into cidade (idCidade, nome, uf) values (218, 'San Diego', 'CA');
insert into cidade (idCidade, nome, uf) values (219, 'Houston', 'TX');
insert into cidade (idCidade, nome, uf) values (220, 'Tucson', 'AZ');
insert into cidade (idCidade, nome, uf) values (221, 'Spokane', 'WA');
insert into cidade (idCidade, nome, uf) values (222, 'Beaufort', 'SC');
insert into cidade (idCidade, nome, uf) values (223, 'Erie', 'PA');
insert into cidade (idCidade, nome, uf) values (224, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (225, 'Baltimore', 'MD');
insert into cidade (idCidade, nome, uf) values (226, 'Glendale', 'CA');
insert into cidade (idCidade, nome, uf) values (227, 'Minneapolis', 'MN');
insert into cidade (idCidade, nome, uf) values (228, 'Lexington', 'KY');
insert into cidade (idCidade, nome, uf) values (229, 'Louisville', 'KY');
insert into cidade (idCidade, nome, uf) values (230, 'Saint Louis', 'MO');
insert into cidade (idCidade, nome, uf) values (231, 'Stamford', 'CT');
insert into cidade (idCidade, nome, uf) values (232, 'Manassas', 'VA');
insert into cidade (idCidade, nome, uf) values (233, 'Memphis', 'TN');
insert into cidade (idCidade, nome, uf) values (234, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (235, 'Detroit', 'MI');
insert into cidade (idCidade, nome, uf) values (236, 'Shawnee Mission', 'KS');
insert into cidade (idCidade, nome, uf) values (237, 'Canton', 'OH');
insert into cidade (idCidade, nome, uf) values (238, 'Saint Louis', 'MO');
insert into cidade (idCidade, nome, uf) values (239, 'Las Vegas', 'NV');
insert into cidade (idCidade, nome, uf) values (240, 'Lincoln', 'NE');
insert into cidade (idCidade, nome, uf) values (241, 'Houston', 'TX');
insert into cidade (idCidade, nome, uf) values (242, 'Miami', 'FL');
insert into cidade (idCidade, nome, uf) values (243, 'Fort Wayne', 'IN');
insert into cidade (idCidade, nome, uf) values (244, 'Orlando', 'FL');
insert into cidade (idCidade, nome, uf) values (245, 'Waco', 'TX');
insert into cidade (idCidade, nome, uf) values (246, 'Huntington Beach', 'CA');
insert into cidade (idCidade, nome, uf) values (247, 'Jacksonville', 'FL');
insert into cidade (idCidade, nome, uf) values (248, 'Columbia', 'SC');
insert into cidade (idCidade, nome, uf) values (249, 'Lawrenceville', 'GA');
insert into cidade (idCidade, nome, uf) values (250, 'Santa Barbara', 'CA');
insert into cidade (idCidade, nome, uf) values (251, 'Flint', 'MI');
insert into cidade (idCidade, nome, uf) values (252, 'Albany', 'NY');
insert into cidade (idCidade, nome, uf) values (253, 'Charlotte', 'NC');
insert into cidade (idCidade, nome, uf) values (254, 'Boynton Beach', 'FL');
insert into cidade (idCidade, nome, uf) values (255, 'Saint Petersburg', 'FL');
insert into cidade (idCidade, nome, uf) values (256, 'Moreno Valley', 'CA');
insert into cidade (idCidade, nome, uf) values (257, 'Houston', 'TX');
insert into cidade (idCidade, nome, uf) values (258, 'San Antonio', 'TX');
insert into cidade (idCidade, nome, uf) values (259, 'Honolulu', 'HI');
insert into cidade (idCidade, nome, uf) values (260, 'Boise', 'ID');
insert into cidade (idCidade, nome, uf) values (261, 'Brooklyn', 'NY');
insert into cidade (idCidade, nome, uf) values (262, 'Pasadena', 'CA');
insert into cidade (idCidade, nome, uf) values (263, 'Raleigh', 'NC');
insert into cidade (idCidade, nome, uf) values (264, 'Albany', 'NY');
insert into cidade (idCidade, nome, uf) values (265, 'Santa Barbara', 'CA');
insert into cidade (idCidade, nome, uf) values (266, 'Lansing', 'MI');
insert into cidade (idCidade, nome, uf) values (267, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (268, 'Austin', 'TX');
insert into cidade (idCidade, nome, uf) values (269, 'Scottsdale', 'AZ');
insert into cidade (idCidade, nome, uf) values (270, 'Peoria', 'IL');
insert into cidade (idCidade, nome, uf) values (271, 'Memphis', 'TN');
insert into cidade (idCidade, nome, uf) values (272, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (273, 'Monticello', 'MN');
insert into cidade (idCidade, nome, uf) values (274, 'Pinellas Park', 'FL');
insert into cidade (idCidade, nome, uf) values (275, 'Chattanooga', 'TN');
insert into cidade (idCidade, nome, uf) values (276, 'Maple Plain', 'MN');
insert into cidade (idCidade, nome, uf) values (277, 'Duluth', 'GA');
insert into cidade (idCidade, nome, uf) values (278, 'Indianapolis', 'IN');
insert into cidade (idCidade, nome, uf) values (279, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (280, 'Fargo', 'ND');
insert into cidade (idCidade, nome, uf) values (281, 'Richmond', 'VA');
insert into cidade (idCidade, nome, uf) values (282, 'Atlanta', 'GA');
insert into cidade (idCidade, nome, uf) values (283, 'Riverside', 'CA');
insert into cidade (idCidade, nome, uf) values (284, 'Akron', 'OH');
insert into cidade (idCidade, nome, uf) values (285, 'Huntsville', 'AL');
insert into cidade (idCidade, nome, uf) values (286, 'Minneapolis', 'MN');
insert into cidade (idCidade, nome, uf) values (287, 'Milwaukee', 'WI');
insert into cidade (idCidade, nome, uf) values (288, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (289, 'Fredericksburg', 'VA');
insert into cidade (idCidade, nome, uf) values (290, 'Jacksonville', 'FL');
insert into cidade (idCidade, nome, uf) values (291, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (292, 'Denton', 'TX');
insert into cidade (idCidade, nome, uf) values (293, 'Wilmington', 'NC');
insert into cidade (idCidade, nome, uf) values (294, 'Philadelphia', 'PA');
insert into cidade (idCidade, nome, uf) values (295, 'Carson City', 'NV');
insert into cidade (idCidade, nome, uf) values (296, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (297, 'Albany', 'NY');
insert into cidade (idCidade, nome, uf) values (298, 'Austin', 'TX');
insert into cidade (idCidade, nome, uf) values (299, 'Lincoln', 'NE');
insert into cidade (idCidade, nome, uf) values (300, 'Richmond', 'VA');
insert into cidade (idCidade, nome, uf) values (301, 'New York City', 'NY');
insert into cidade (idCidade, nome, uf) values (302, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (303, 'Buffalo', 'NY');
insert into cidade (idCidade, nome, uf) values (304, 'Monticello', 'MN');
insert into cidade (idCidade, nome, uf) values (305, 'Oklahoma City', 'OK');
insert into cidade (idCidade, nome, uf) values (306, 'New Orleans', 'LA');
insert into cidade (idCidade, nome, uf) values (307, 'New York City', 'NY');
insert into cidade (idCidade, nome, uf) values (308, 'Camden', 'NJ');
insert into cidade (idCidade, nome, uf) values (309, 'Stockton', 'CA');
insert into cidade (idCidade, nome, uf) values (310, 'Honolulu', 'HI');
insert into cidade (idCidade, nome, uf) values (311, 'Lawrenceville', 'GA');
insert into cidade (idCidade, nome, uf) values (312, 'Lancaster', 'PA');
insert into cidade (idCidade, nome, uf) values (313, 'Dallas', 'TX');
insert into cidade (idCidade, nome, uf) values (314, 'Rochester', 'NY');
insert into cidade (idCidade, nome, uf) values (315, 'Hartford', 'CT');
insert into cidade (idCidade, nome, uf) values (316, 'Knoxville', 'TN');
insert into cidade (idCidade, nome, uf) values (317, 'Houston', 'TX');
insert into cidade (idCidade, nome, uf) values (318, 'Troy', 'MI');
insert into cidade (idCidade, nome, uf) values (319, 'Saint Paul', 'MN');
insert into cidade (idCidade, nome, uf) values (320, 'Hartford', 'CT');
insert into cidade (idCidade, nome, uf) values (321, 'Charlotte', 'NC');
insert into cidade (idCidade, nome, uf) values (322, 'Huntington Beach', 'CA');
insert into cidade (idCidade, nome, uf) values (323, 'Gary', 'IN');
insert into cidade (idCidade, nome, uf) values (324, 'Hattiesburg', 'MS');
insert into cidade (idCidade, nome, uf) values (325, 'Tucson', 'AZ');
insert into cidade (idCidade, nome, uf) values (326, 'Anniston', 'AL');
insert into cidade (idCidade, nome, uf) values (327, 'Arlington', 'VA');
insert into cidade (idCidade, nome, uf) values (328, 'Philadelphia', 'PA');
insert into cidade (idCidade, nome, uf) values (329, 'Los Angeles', 'CA');
insert into cidade (idCidade, nome, uf) values (330, 'Appleton', 'WI');
insert into cidade (idCidade, nome, uf) values (331, 'Lancaster', 'PA');
insert into cidade (idCidade, nome, uf) values (332, 'Lansing', 'MI');
insert into cidade (idCidade, nome, uf) values (333, 'Tucson', 'AZ');
insert into cidade (idCidade, nome, uf) values (334, 'Columbia', 'SC');
insert into cidade (idCidade, nome, uf) values (335, 'Cleveland', 'OH');
insert into cidade (idCidade, nome, uf) values (336, 'Orlando', 'FL');
insert into cidade (idCidade, nome, uf) values (337, 'Silver Spring', 'MD');
insert into cidade (idCidade, nome, uf) values (338, 'San Luis Obispo', 'CA');
insert into cidade (idCidade, nome, uf) values (339, 'Minneapolis', 'MN');
insert into cidade (idCidade, nome, uf) values (340, 'Lake Worth', 'FL');
insert into cidade (idCidade, nome, uf) values (341, 'Phoenix', 'AZ');
insert into cidade (idCidade, nome, uf) values (342, 'Nashville', 'TN');
insert into cidade (idCidade, nome, uf) values (343, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (344, 'Elizabeth', 'NJ');
insert into cidade (idCidade, nome, uf) values (345, 'Bismarck', 'ND');
insert into cidade (idCidade, nome, uf) values (346, 'Ocala', 'FL');
insert into cidade (idCidade, nome, uf) values (347, 'Garland', 'TX');
insert into cidade (idCidade, nome, uf) values (348, 'San Diego', 'CA');
insert into cidade (idCidade, nome, uf) values (349, 'Tucson', 'AZ');
insert into cidade (idCidade, nome, uf) values (350, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (351, 'Rochester', 'NY');
insert into cidade (idCidade, nome, uf) values (352, 'Baltimore', 'MD');
insert into cidade (idCidade, nome, uf) values (353, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (354, 'Pasadena', 'CA');
insert into cidade (idCidade, nome, uf) values (355, 'Boulder', 'CO');
insert into cidade (idCidade, nome, uf) values (356, 'Las Vegas', 'NV');
insert into cidade (idCidade, nome, uf) values (357, 'Missoula', 'MT');
insert into cidade (idCidade, nome, uf) values (358, 'Jefferson City', 'MO');
insert into cidade (idCidade, nome, uf) values (359, 'Brooklyn', 'NY');
insert into cidade (idCidade, nome, uf) values (360, 'San Mateo', 'CA');
insert into cidade (idCidade, nome, uf) values (361, 'Kansas City', 'MO');
insert into cidade (idCidade, nome, uf) values (362, 'Cincinnati', 'OH');
insert into cidade (idCidade, nome, uf) values (363, 'Nashville', 'TN');
insert into cidade (idCidade, nome, uf) values (364, 'Fort Worth', 'TX');
insert into cidade (idCidade, nome, uf) values (365, 'Indianapolis', 'IN');
insert into cidade (idCidade, nome, uf) values (366, 'Stockton', 'CA');
insert into cidade (idCidade, nome, uf) values (367, 'New York City', 'NY');
insert into cidade (idCidade, nome, uf) values (368, 'Atlanta', 'GA');
insert into cidade (idCidade, nome, uf) values (369, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (370, 'Gary', 'IN');
insert into cidade (idCidade, nome, uf) values (371, 'Orlando', 'FL');
insert into cidade (idCidade, nome, uf) values (372, 'Louisville', 'KY');
insert into cidade (idCidade, nome, uf) values (373, 'Fort Wayne', 'IN');
insert into cidade (idCidade, nome, uf) values (374, 'Pittsburgh', 'PA');
insert into cidade (idCidade, nome, uf) values (375, 'Chicago', 'IL');
insert into cidade (idCidade, nome, uf) values (376, 'San Diego', 'CA');
insert into cidade (idCidade, nome, uf) values (377, 'Houston', 'TX');
insert into cidade (idCidade, nome, uf) values (378, 'Lansing', 'MI');
insert into cidade (idCidade, nome, uf) values (379, 'Peoria', 'AZ');
insert into cidade (idCidade, nome, uf) values (380, 'Salt Lake City', 'UT');
insert into cidade (idCidade, nome, uf) values (381, 'Rochester', 'NY');
insert into cidade (idCidade, nome, uf) values (382, 'Baltimore', 'MD');
insert into cidade (idCidade, nome, uf) values (383, 'Mountain View', 'CA');
insert into cidade (idCidade, nome, uf) values (384, 'Cleveland', 'OH');
insert into cidade (idCidade, nome, uf) values (385, 'Redwood City', 'CA');
insert into cidade (idCidade, nome, uf) values (386, 'Kansas City', 'KS');
insert into cidade (idCidade, nome, uf) values (387, 'Little Rock', 'AR');
insert into cidade (idCidade, nome, uf) values (388, 'Dallas', 'TX');
insert into cidade (idCidade, nome, uf) values (389, 'Wilmington', 'NC');
insert into cidade (idCidade, nome, uf) values (390, 'Tacoma', 'WA');
insert into cidade (idCidade, nome, uf) values (391, 'Pittsburgh', 'PA');
insert into cidade (idCidade, nome, uf) values (392, 'Nashville', 'TN');
insert into cidade (idCidade, nome, uf) values (393, 'Long Beach', 'CA');
insert into cidade (idCidade, nome, uf) values (394, 'Richmond', 'VA');
insert into cidade (idCidade, nome, uf) values (395, 'Brooklyn', 'NY');
insert into cidade (idCidade, nome, uf) values (396, 'Atlanta', 'GA');
insert into cidade (idCidade, nome, uf) values (397, 'Boulder', 'CO');
insert into cidade (idCidade, nome, uf) values (398, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (399, 'Tulsa', 'OK');
insert into cidade (idCidade, nome, uf) values (400, 'Cincinnati', 'OH');
insert into cidade (idCidade, nome, uf) values (401, 'Kansas City', 'MO');
insert into cidade (idCidade, nome, uf) values (402, 'Jacksonville', 'FL');
insert into cidade (idCidade, nome, uf) values (403, 'Aurora', 'CO');
insert into cidade (idCidade, nome, uf) values (404, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (405, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (406, 'Anchorage', 'AK');
insert into cidade (idCidade, nome, uf) values (407, 'Englewood', 'CO');
insert into cidade (idCidade, nome, uf) values (408, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (409, 'Boise', 'ID');
insert into cidade (idCidade, nome, uf) values (410, 'Des Moines', 'IA');
insert into cidade (idCidade, nome, uf) values (411, 'Greensboro', 'NC');
insert into cidade (idCidade, nome, uf) values (412, 'Gastonia', 'NC');
insert into cidade (idCidade, nome, uf) values (413, 'Waco', 'TX');
insert into cidade (idCidade, nome, uf) values (414, 'Newark', 'NJ');
insert into cidade (idCidade, nome, uf) values (415, 'Wilmington', 'DE');
insert into cidade (idCidade, nome, uf) values (416, 'Madison', 'WI');
insert into cidade (idCidade, nome, uf) values (417, 'Baton Rouge', 'LA');
insert into cidade (idCidade, nome, uf) values (418, 'San Diego', 'CA');
insert into cidade (idCidade, nome, uf) values (419, 'Jacksonville', 'FL');
insert into cidade (idCidade, nome, uf) values (420, 'Atlanta', 'GA');
insert into cidade (idCidade, nome, uf) values (421, 'Los Angeles', 'CA');
insert into cidade (idCidade, nome, uf) values (422, 'Corpus Christi', 'TX');
insert into cidade (idCidade, nome, uf) values (423, 'Salt Lake City', 'UT');
insert into cidade (idCidade, nome, uf) values (424, 'Pittsburgh', 'PA');
insert into cidade (idCidade, nome, uf) values (425, 'Appleton', 'WI');
insert into cidade (idCidade, nome, uf) values (426, 'Wichita', 'KS');
insert into cidade (idCidade, nome, uf) values (427, 'Toledo', 'OH');
insert into cidade (idCidade, nome, uf) values (428, 'Fort Wayne', 'IN');
insert into cidade (idCidade, nome, uf) values (429, 'Arlington', 'TX');
insert into cidade (idCidade, nome, uf) values (430, 'Wilkes Barre', 'PA');
insert into cidade (idCidade, nome, uf) values (431, 'Saint Paul', 'MN');
insert into cidade (idCidade, nome, uf) values (432, 'Waterloo', 'IA');
insert into cidade (idCidade, nome, uf) values (433, 'Canton', 'OH');
insert into cidade (idCidade, nome, uf) values (434, 'North Las Vegas', 'NV');
insert into cidade (idCidade, nome, uf) values (435, 'Beaufort', 'SC');
insert into cidade (idCidade, nome, uf) values (436, 'Pueblo', 'CO');
insert into cidade (idCidade, nome, uf) values (437, 'Spring', 'TX');
insert into cidade (idCidade, nome, uf) values (438, 'Saint Petersburg', 'FL');
insert into cidade (idCidade, nome, uf) values (439, 'Odessa', 'TX');
insert into cidade (idCidade, nome, uf) values (440, 'Littleton', 'CO');
insert into cidade (idCidade, nome, uf) values (441, 'Spartanburg', 'SC');
insert into cidade (idCidade, nome, uf) values (442, 'Scottsdale', 'AZ');
insert into cidade (idCidade, nome, uf) values (443, 'Atlanta', 'GA');
insert into cidade (idCidade, nome, uf) values (444, 'Orlando', 'FL');
insert into cidade (idCidade, nome, uf) values (445, 'Newark', 'NJ');
insert into cidade (idCidade, nome, uf) values (446, 'Springfield', 'MO');
insert into cidade (idCidade, nome, uf) values (447, 'Santa Cruz', 'CA');
insert into cidade (idCidade, nome, uf) values (448, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (449, 'Newport News', 'VA');
insert into cidade (idCidade, nome, uf) values (450, 'Mobile', 'AL');
insert into cidade (idCidade, nome, uf) values (451, 'San Jose', 'CA');
insert into cidade (idCidade, nome, uf) values (452, 'Worcester', 'MA');
insert into cidade (idCidade, nome, uf) values (453, 'Omaha', 'NE');
insert into cidade (idCidade, nome, uf) values (454, 'Shreveport', 'LA');
insert into cidade (idCidade, nome, uf) values (455, 'Jackson', 'TN');
insert into cidade (idCidade, nome, uf) values (456, 'Albany', 'NY');
insert into cidade (idCidade, nome, uf) values (457, 'Florence', 'SC');
insert into cidade (idCidade, nome, uf) values (458, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (459, 'Sioux Falls', 'SD');
insert into cidade (idCidade, nome, uf) values (460, 'Hampton', 'VA');
insert into cidade (idCidade, nome, uf) values (461, 'Orlando', 'FL');
insert into cidade (idCidade, nome, uf) values (462, 'Denver', 'CO');
insert into cidade (idCidade, nome, uf) values (463, 'Kansas City', 'MO');
insert into cidade (idCidade, nome, uf) values (464, 'Denver', 'CO');
insert into cidade (idCidade, nome, uf) values (465, 'Tampa', 'FL');
insert into cidade (idCidade, nome, uf) values (466, 'Hicksville', 'NY');
insert into cidade (idCidade, nome, uf) values (467, 'Northridge', 'CA');
insert into cidade (idCidade, nome, uf) values (468, 'Albany', 'NY');
insert into cidade (idCidade, nome, uf) values (469, 'Spokane', 'WA');
insert into cidade (idCidade, nome, uf) values (470, 'Bradenton', 'FL');
insert into cidade (idCidade, nome, uf) values (471, 'Mountain View', 'CA');
insert into cidade (idCidade, nome, uf) values (472, 'Hot Springs National Park', 'AR');
insert into cidade (idCidade, nome, uf) values (473, 'Naples', 'FL');
insert into cidade (idCidade, nome, uf) values (474, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (475, 'Richmond', 'VA');
insert into cidade (idCidade, nome, uf) values (476, 'Santa Monica', 'CA');
insert into cidade (idCidade, nome, uf) values (477, 'Albuquerque', 'NM');
insert into cidade (idCidade, nome, uf) values (478, 'Fort Myers', 'FL');
insert into cidade (idCidade, nome, uf) values (479, 'Canton', 'OH');
insert into cidade (idCidade, nome, uf) values (480, 'Las Vegas', 'NV');
insert into cidade (idCidade, nome, uf) values (481, 'Garland', 'TX');
insert into cidade (idCidade, nome, uf) values (482, 'Silver Spring', 'MD');
insert into cidade (idCidade, nome, uf) values (483, 'Fresno', 'CA');
insert into cidade (idCidade, nome, uf) values (484, 'Seattle', 'WA');
insert into cidade (idCidade, nome, uf) values (485, 'Houston', 'TX');
insert into cidade (idCidade, nome, uf) values (486, 'Albany', 'NY');
insert into cidade (idCidade, nome, uf) values (487, 'Louisville', 'KY');
insert into cidade (idCidade, nome, uf) values (488, 'Atlanta', 'GA');
insert into cidade (idCidade, nome, uf) values (489, 'Salt Lake City', 'UT');
insert into cidade (idCidade, nome, uf) values (490, 'Newark', 'NJ');
insert into cidade (idCidade, nome, uf) values (491, 'Santa Fe', 'NM');
insert into cidade (idCidade, nome, uf) values (492, 'Alhambra', 'CA');
insert into cidade (idCidade, nome, uf) values (493, 'Austin', 'TX');
insert into cidade (idCidade, nome, uf) values (494, 'Greeley', 'CO');
insert into cidade (idCidade, nome, uf) values (495, 'Tyler', 'TX');
insert into cidade (idCidade, nome, uf) values (496, 'Charlotte', 'NC');
insert into cidade (idCidade, nome, uf) values (497, 'Vero Beach', 'FL');
insert into cidade (idCidade, nome, uf) values (498, 'Dayton', 'OH');
insert into cidade (idCidade, nome, uf) values (499, 'Mobile', 'AL');
insert into cidade (idCidade, nome, uf) values (500, 'Honolulu', 'HI');
insert into cidade (idCidade, nome, uf) values (501, 'Jackson', 'MS');
insert into cidade (idCidade, nome, uf) values (502, 'Flushing', 'NY');
insert into cidade (idCidade, nome, uf) values (503, 'Phoenix', 'AZ');
insert into cidade (idCidade, nome, uf) values (504, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (505, 'Little Rock', 'AR');
insert into cidade (idCidade, nome, uf) values (506, 'North Hollywood', 'CA');
insert into cidade (idCidade, nome, uf) values (507, 'Saint Cloud', 'MN');
insert into cidade (idCidade, nome, uf) values (508, 'Aurora', 'CO');
insert into cidade (idCidade, nome, uf) values (509, 'Boston', 'MA');
insert into cidade (idCidade, nome, uf) values (510, 'Lubbock', 'TX');
insert into cidade (idCidade, nome, uf) values (511, 'Murfreesboro', 'TN');
insert into cidade (idCidade, nome, uf) values (512, 'Murfreesboro', 'TN');
insert into cidade (idCidade, nome, uf) values (513, 'Newton', 'MA');
insert into cidade (idCidade, nome, uf) values (514, 'Helena', 'MT');
insert into cidade (idCidade, nome, uf) values (515, 'Helena', 'MT');
insert into cidade (idCidade, nome, uf) values (516, 'Stockton', 'CA');
insert into cidade (idCidade, nome, uf) values (517, 'Raleigh', 'NC');
insert into cidade (idCidade, nome, uf) values (518, 'Boston', 'MA');
insert into cidade (idCidade, nome, uf) values (519, 'Huntington', 'WV');
insert into cidade (idCidade, nome, uf) values (520, 'Billings', 'MT');
insert into cidade (idCidade, nome, uf) values (521, 'Pittsburgh', 'PA');
insert into cidade (idCidade, nome, uf) values (522, 'Pompano Beach', 'FL');
insert into cidade (idCidade, nome, uf) values (523, 'Oklahoma City', 'OK');
insert into cidade (idCidade, nome, uf) values (524, 'Evansville', 'IN');
insert into cidade (idCidade, nome, uf) values (525, 'Hialeah', 'FL');
insert into cidade (idCidade, nome, uf) values (526, 'Richmond', 'VA');
insert into cidade (idCidade, nome, uf) values (527, 'Miami', 'FL');
insert into cidade (idCidade, nome, uf) values (528, 'San Luis Obispo', 'CA');
insert into cidade (idCidade, nome, uf) values (529, 'Newport Beach', 'CA');
insert into cidade (idCidade, nome, uf) values (530, 'San Antonio', 'TX');
insert into cidade (idCidade, nome, uf) values (531, 'Wichita', 'KS');
insert into cidade (idCidade, nome, uf) values (532, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (533, 'Columbia', 'MO');
insert into cidade (idCidade, nome, uf) values (534, 'Kansas City', 'MO');
insert into cidade (idCidade, nome, uf) values (535, 'New York City', 'NY');
insert into cidade (idCidade, nome, uf) values (536, 'New Orleans', 'LA');
insert into cidade (idCidade, nome, uf) values (537, 'Reading', 'PA');
insert into cidade (idCidade, nome, uf) values (538, 'Houston', 'TX');
insert into cidade (idCidade, nome, uf) values (539, 'Miami', 'FL');
insert into cidade (idCidade, nome, uf) values (540, 'Des Moines', 'IA');
insert into cidade (idCidade, nome, uf) values (541, 'Aurora', 'CO');
insert into cidade (idCidade, nome, uf) values (542, 'Cleveland', 'OH');
insert into cidade (idCidade, nome, uf) values (543, 'Austin', 'TX');
insert into cidade (idCidade, nome, uf) values (544, 'Irving', 'TX');
insert into cidade (idCidade, nome, uf) values (545, 'Orlando', 'FL');
insert into cidade (idCidade, nome, uf) values (546, 'Denver', 'CO');
insert into cidade (idCidade, nome, uf) values (547, 'Denver', 'CO');
insert into cidade (idCidade, nome, uf) values (548, 'Fargo', 'ND');
insert into cidade (idCidade, nome, uf) values (549, 'Austin', 'TX');
insert into cidade (idCidade, nome, uf) values (550, 'Pasadena', 'TX');
insert into cidade (idCidade, nome, uf) values (551, 'Fort Wayne', 'IN');
insert into cidade (idCidade, nome, uf) values (552, 'Richmond', 'VA');
insert into cidade (idCidade, nome, uf) values (553, 'Dayton', 'OH');
insert into cidade (idCidade, nome, uf) values (554, 'Cincinnati', 'OH');
insert into cidade (idCidade, nome, uf) values (555, 'New Orleans', 'LA');
insert into cidade (idCidade, nome, uf) values (556, 'Norfolk', 'VA');
insert into cidade (idCidade, nome, uf) values (557, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (558, 'Saint Paul', 'MN');
insert into cidade (idCidade, nome, uf) values (559, 'Rochester', 'NY');
insert into cidade (idCidade, nome, uf) values (560, 'Phoenix', 'AZ');
insert into cidade (idCidade, nome, uf) values (561, 'Ashburn', 'VA');
insert into cidade (idCidade, nome, uf) values (562, 'Anaheim', 'CA');
insert into cidade (idCidade, nome, uf) values (563, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (564, 'Houston', 'TX');
insert into cidade (idCidade, nome, uf) values (565, 'Tucson', 'AZ');
insert into cidade (idCidade, nome, uf) values (566, 'Rochester', 'MN');
insert into cidade (idCidade, nome, uf) values (567, 'Mesquite', 'TX');
insert into cidade (idCidade, nome, uf) values (568, 'Philadelphia', 'PA');
insert into cidade (idCidade, nome, uf) values (569, 'Philadelphia', 'PA');
insert into cidade (idCidade, nome, uf) values (570, 'Reno', 'NV');
insert into cidade (idCidade, nome, uf) values (571, 'Pasadena', 'CA');
insert into cidade (idCidade, nome, uf) values (572, 'Spokane', 'WA');
insert into cidade (idCidade, nome, uf) values (573, 'Kansas City', 'KS');
insert into cidade (idCidade, nome, uf) values (574, 'Philadelphia', 'PA');
insert into cidade (idCidade, nome, uf) values (575, 'Flint', 'MI');
insert into cidade (idCidade, nome, uf) values (576, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (577, 'Bradenton', 'FL');
insert into cidade (idCidade, nome, uf) values (578, 'Charlottesville', 'VA');
insert into cidade (idCidade, nome, uf) values (579, 'Bronx', 'NY');
insert into cidade (idCidade, nome, uf) values (580, 'Akron', 'OH');
insert into cidade (idCidade, nome, uf) values (581, 'Odessa', 'TX');
insert into cidade (idCidade, nome, uf) values (582, 'Brooklyn', 'NY');
insert into cidade (idCidade, nome, uf) values (583, 'Boston', 'MA');
insert into cidade (idCidade, nome, uf) values (584, 'San Rafael', 'CA');
insert into cidade (idCidade, nome, uf) values (585, 'Norcross', 'GA');
insert into cidade (idCidade, nome, uf) values (586, 'South Bend', 'IN');
insert into cidade (idCidade, nome, uf) values (587, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (588, 'Glendale', 'CA');
insert into cidade (idCidade, nome, uf) values (589, 'Greenville', 'SC');
insert into cidade (idCidade, nome, uf) values (590, 'Pomona', 'CA');
insert into cidade (idCidade, nome, uf) values (591, 'Nashville', 'TN');
insert into cidade (idCidade, nome, uf) values (592, 'Springfield', 'IL');
insert into cidade (idCidade, nome, uf) values (593, 'Los Angeles', 'CA');
insert into cidade (idCidade, nome, uf) values (594, 'Jefferson City', 'MO');
insert into cidade (idCidade, nome, uf) values (595, 'New York City', 'NY');
insert into cidade (idCidade, nome, uf) values (596, 'Bakersfield', 'CA');
insert into cidade (idCidade, nome, uf) values (597, 'New York City', 'NY');
insert into cidade (idCidade, nome, uf) values (598, 'Pasadena', 'CA');
insert into cidade (idCidade, nome, uf) values (599, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (600, 'Austin', 'TX');
insert into cidade (idCidade, nome, uf) values (601, 'Montgomery', 'AL');
insert into cidade (idCidade, nome, uf) values (602, 'Irving', 'TX');
insert into cidade (idCidade, nome, uf) values (603, 'Mobile', 'AL');
insert into cidade (idCidade, nome, uf) values (604, 'Topeka', 'KS');
insert into cidade (idCidade, nome, uf) values (605, 'Tucson', 'AZ');
insert into cidade (idCidade, nome, uf) values (606, 'Boise', 'ID');
insert into cidade (idCidade, nome, uf) values (607, 'Huntington', 'WV');
insert into cidade (idCidade, nome, uf) values (608, 'Saint Petersburg', 'FL');
insert into cidade (idCidade, nome, uf) values (609, 'Fort Worth', 'TX');
insert into cidade (idCidade, nome, uf) values (610, 'Arlington', 'VA');
insert into cidade (idCidade, nome, uf) values (611, 'Humble', 'TX');
insert into cidade (idCidade, nome, uf) values (612, 'Jersey City', 'NJ');
insert into cidade (idCidade, nome, uf) values (613, 'New Haven', 'CT');
insert into cidade (idCidade, nome, uf) values (614, 'Charlotte', 'NC');
insert into cidade (idCidade, nome, uf) values (615, 'Bridgeport', 'CT');
insert into cidade (idCidade, nome, uf) values (616, 'Tacoma', 'WA');
insert into cidade (idCidade, nome, uf) values (617, 'Colorado Springs', 'CO');
insert into cidade (idCidade, nome, uf) values (618, 'Athens', 'GA');
insert into cidade (idCidade, nome, uf) values (619, 'Scottsdale', 'AZ');
insert into cidade (idCidade, nome, uf) values (620, 'Young America', 'MN');
insert into cidade (idCidade, nome, uf) values (621, 'Fort Pierce', 'FL');
insert into cidade (idCidade, nome, uf) values (622, 'Fresno', 'CA');
insert into cidade (idCidade, nome, uf) values (623, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (624, 'Jamaica', 'NY');
insert into cidade (idCidade, nome, uf) values (625, 'Salt Lake City', 'UT');
insert into cidade (idCidade, nome, uf) values (626, 'Columbia', 'SC');
insert into cidade (idCidade, nome, uf) values (627, 'Jackson', 'MS');
insert into cidade (idCidade, nome, uf) values (628, 'Huntington', 'WV');
insert into cidade (idCidade, nome, uf) values (629, 'Myrtle Beach', 'SC');
insert into cidade (idCidade, nome, uf) values (630, 'Denver', 'CO');
insert into cidade (idCidade, nome, uf) values (631, 'Kansas City', 'MO');
insert into cidade (idCidade, nome, uf) values (632, 'Milwaukee', 'WI');
insert into cidade (idCidade, nome, uf) values (633, 'Glendale', 'AZ');
insert into cidade (idCidade, nome, uf) values (634, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (635, 'Saint Louis', 'MO');
insert into cidade (idCidade, nome, uf) values (636, 'Pensacola', 'FL');
insert into cidade (idCidade, nome, uf) values (637, 'Charlottesville', 'VA');
insert into cidade (idCidade, nome, uf) values (638, 'Charleston', 'WV');
insert into cidade (idCidade, nome, uf) values (639, 'Huntsville', 'AL');
insert into cidade (idCidade, nome, uf) values (640, 'Anderson', 'SC');
insert into cidade (idCidade, nome, uf) values (641, 'Garland', 'TX');
insert into cidade (idCidade, nome, uf) values (642, 'Tampa', 'FL');
insert into cidade (idCidade, nome, uf) values (643, 'Charlotte', 'NC');
insert into cidade (idCidade, nome, uf) values (644, 'Phoenix', 'AZ');
insert into cidade (idCidade, nome, uf) values (645, 'Cleveland', 'OH');
insert into cidade (idCidade, nome, uf) values (646, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (647, 'San Jose', 'CA');
insert into cidade (idCidade, nome, uf) values (648, 'Richmond', 'VA');
insert into cidade (idCidade, nome, uf) values (649, 'Huntington', 'WV');
insert into cidade (idCidade, nome, uf) values (650, 'Boise', 'ID');
insert into cidade (idCidade, nome, uf) values (651, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (652, 'Denver', 'CO');
insert into cidade (idCidade, nome, uf) values (653, 'Jacksonville', 'FL');
insert into cidade (idCidade, nome, uf) values (654, 'Waco', 'TX');
insert into cidade (idCidade, nome, uf) values (655, 'Lexington', 'KY');
insert into cidade (idCidade, nome, uf) values (656, 'Spartanburg', 'SC');
insert into cidade (idCidade, nome, uf) values (657, 'San Francisco', 'CA');
insert into cidade (idCidade, nome, uf) values (658, 'Los Angeles', 'CA');
insert into cidade (idCidade, nome, uf) values (659, 'Cincinnati', 'OH');
insert into cidade (idCidade, nome, uf) values (660, 'San Antonio', 'TX');
insert into cidade (idCidade, nome, uf) values (661, 'Tulsa', 'OK');
insert into cidade (idCidade, nome, uf) values (662, 'Lehigh Acres', 'FL');
insert into cidade (idCidade, nome, uf) values (663, 'San Antonio', 'TX');
insert into cidade (idCidade, nome, uf) values (664, 'Wilmington', 'NC');
insert into cidade (idCidade, nome, uf) values (665, 'Arlington', 'TX');
insert into cidade (idCidade, nome, uf) values (666, 'Seattle', 'WA');
insert into cidade (idCidade, nome, uf) values (667, 'Hartford', 'CT');
insert into cidade (idCidade, nome, uf) values (668, 'Flint', 'MI');
insert into cidade (idCidade, nome, uf) values (669, 'Plano', 'TX');
insert into cidade (idCidade, nome, uf) values (670, 'Salt Lake City', 'UT');
insert into cidade (idCidade, nome, uf) values (671, 'Baltimore', 'MD');
insert into cidade (idCidade, nome, uf) values (672, 'Paterson', 'NJ');
insert into cidade (idCidade, nome, uf) values (673, 'Roanoke', 'VA');
insert into cidade (idCidade, nome, uf) values (674, 'Charlottesville', 'VA');
insert into cidade (idCidade, nome, uf) values (675, 'Bradenton', 'FL');
insert into cidade (idCidade, nome, uf) values (676, 'Grand Rapids', 'MI');
insert into cidade (idCidade, nome, uf) values (677, 'Bridgeport', 'CT');
insert into cidade (idCidade, nome, uf) values (678, 'Pasadena', 'CA');
insert into cidade (idCidade, nome, uf) values (679, 'Salt Lake City', 'UT');
insert into cidade (idCidade, nome, uf) values (680, 'Montgomery', 'AL');
insert into cidade (idCidade, nome, uf) values (681, 'Laredo', 'TX');
insert into cidade (idCidade, nome, uf) values (682, 'Denver', 'CO');
insert into cidade (idCidade, nome, uf) values (683, 'Boston', 'MA');
insert into cidade (idCidade, nome, uf) values (684, 'Brooklyn', 'NY');
insert into cidade (idCidade, nome, uf) values (685, 'Clearwater', 'FL');
insert into cidade (idCidade, nome, uf) values (686, 'Santa Monica', 'CA');
insert into cidade (idCidade, nome, uf) values (687, 'Chico', 'CA');
insert into cidade (idCidade, nome, uf) values (688, 'Midland', 'TX');
insert into cidade (idCidade, nome, uf) values (689, 'San Diego', 'CA');
insert into cidade (idCidade, nome, uf) values (690, 'Springfield', 'MO');
insert into cidade (idCidade, nome, uf) values (691, 'Brooklyn', 'NY');
insert into cidade (idCidade, nome, uf) values (692, 'Knoxville', 'TN');
insert into cidade (idCidade, nome, uf) values (693, 'North Hollywood', 'CA');
insert into cidade (idCidade, nome, uf) values (694, 'San Francisco', 'CA');
insert into cidade (idCidade, nome, uf) values (695, 'New York City', 'NY');
insert into cidade (idCidade, nome, uf) values (696, 'Cleveland', 'OH');
insert into cidade (idCidade, nome, uf) values (697, 'Baton Rouge', 'LA');
insert into cidade (idCidade, nome, uf) values (698, 'Waterbury', 'CT');
insert into cidade (idCidade, nome, uf) values (699, 'Midland', 'TX');
insert into cidade (idCidade, nome, uf) values (700, 'Minneapolis', 'MN');
insert into cidade (idCidade, nome, uf) values (701, 'Harrisburg', 'PA');
insert into cidade (idCidade, nome, uf) values (702, 'Chicago', 'IL');
insert into cidade (idCidade, nome, uf) values (703, 'New York City', 'NY');
insert into cidade (idCidade, nome, uf) values (704, 'Daytona Beach', 'FL');
insert into cidade (idCidade, nome, uf) values (705, 'Boston', 'MA');
insert into cidade (idCidade, nome, uf) values (706, 'Trenton', 'NJ');
insert into cidade (idCidade, nome, uf) values (707, 'Flint', 'MI');
insert into cidade (idCidade, nome, uf) values (708, 'Colorado Springs', 'CO');
insert into cidade (idCidade, nome, uf) values (709, 'Erie', 'PA');
insert into cidade (idCidade, nome, uf) values (710, 'Wichita', 'KS');
insert into cidade (idCidade, nome, uf) values (711, 'Little Rock', 'AR');
insert into cidade (idCidade, nome, uf) values (712, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (713, 'Austin', 'TX');
insert into cidade (idCidade, nome, uf) values (714, 'Abilene', 'TX');
insert into cidade (idCidade, nome, uf) values (715, 'Brooklyn', 'NY');
insert into cidade (idCidade, nome, uf) values (716, 'Tampa', 'FL');
insert into cidade (idCidade, nome, uf) values (717, 'Laredo', 'TX');
insert into cidade (idCidade, nome, uf) values (718, 'Mobile', 'AL');
insert into cidade (idCidade, nome, uf) values (719, 'Charleston', 'WV');
insert into cidade (idCidade, nome, uf) values (720, 'Las Vegas', 'NV');
insert into cidade (idCidade, nome, uf) values (721, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (722, 'Scottsdale', 'AZ');
insert into cidade (idCidade, nome, uf) values (723, 'Arlington', 'TX');
insert into cidade (idCidade, nome, uf) values (724, 'Louisville', 'KY');
insert into cidade (idCidade, nome, uf) values (725, 'Pasadena', 'CA');
insert into cidade (idCidade, nome, uf) values (726, 'Chicago', 'IL');
insert into cidade (idCidade, nome, uf) values (727, 'Huntington', 'WV');
insert into cidade (idCidade, nome, uf) values (728, 'Newark', 'NJ');
insert into cidade (idCidade, nome, uf) values (729, 'Jeffersonville', 'IN');
insert into cidade (idCidade, nome, uf) values (730, 'Odessa', 'TX');
insert into cidade (idCidade, nome, uf) values (731, 'Little Rock', 'AR');
insert into cidade (idCidade, nome, uf) values (732, 'Stockton', 'CA');
insert into cidade (idCidade, nome, uf) values (733, 'Toledo', 'OH');
insert into cidade (idCidade, nome, uf) values (734, 'Amarillo', 'TX');
insert into cidade (idCidade, nome, uf) values (735, 'Omaha', 'NE');
insert into cidade (idCidade, nome, uf) values (736, 'Stockton', 'CA');
insert into cidade (idCidade, nome, uf) values (737, 'Miami', 'FL');
insert into cidade (idCidade, nome, uf) values (738, 'San Jose', 'CA');
insert into cidade (idCidade, nome, uf) values (739, 'Minneapolis', 'MN');
insert into cidade (idCidade, nome, uf) values (740, 'Oakland', 'CA');
insert into cidade (idCidade, nome, uf) values (741, 'Houston', 'TX');
insert into cidade (idCidade, nome, uf) values (742, 'Edmond', 'OK');
insert into cidade (idCidade, nome, uf) values (743, 'Berkeley', 'CA');
insert into cidade (idCidade, nome, uf) values (744, 'Paterson', 'NJ');
insert into cidade (idCidade, nome, uf) values (745, 'New York City', 'NY');
insert into cidade (idCidade, nome, uf) values (746, 'Bellevue', 'WA');
insert into cidade (idCidade, nome, uf) values (747, 'Columbia', 'SC');
insert into cidade (idCidade, nome, uf) values (748, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (749, 'Tampa', 'FL');
insert into cidade (idCidade, nome, uf) values (750, 'San Antonio', 'TX');
insert into cidade (idCidade, nome, uf) values (751, 'Winter Haven', 'FL');
insert into cidade (idCidade, nome, uf) values (752, 'Las Cruces', 'NM');
insert into cidade (idCidade, nome, uf) values (753, 'Corpus Christi', 'TX');
insert into cidade (idCidade, nome, uf) values (754, 'Albany', 'NY');
insert into cidade (idCidade, nome, uf) values (755, 'Lexington', 'KY');
insert into cidade (idCidade, nome, uf) values (756, 'Pittsburgh', 'PA');
insert into cidade (idCidade, nome, uf) values (757, 'San Francisco', 'CA');
insert into cidade (idCidade, nome, uf) values (758, 'Des Moines', 'IA');
insert into cidade (idCidade, nome, uf) values (759, 'Garland', 'TX');
insert into cidade (idCidade, nome, uf) values (760, 'Charlotte', 'NC');
insert into cidade (idCidade, nome, uf) values (761, 'Bakersfield', 'CA');
insert into cidade (idCidade, nome, uf) values (762, 'Charleston', 'WV');
insert into cidade (idCidade, nome, uf) values (763, 'Albuquerque', 'NM');
insert into cidade (idCidade, nome, uf) values (764, 'Arlington', 'TX');
insert into cidade (idCidade, nome, uf) values (765, 'Columbia', 'SC');
insert into cidade (idCidade, nome, uf) values (766, 'Young America', 'MN');
insert into cidade (idCidade, nome, uf) values (767, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (768, 'Anaheim', 'CA');
insert into cidade (idCidade, nome, uf) values (769, 'Atlanta', 'GA');
insert into cidade (idCidade, nome, uf) values (770, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (771, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (772, 'Baltimore', 'MD');
insert into cidade (idCidade, nome, uf) values (773, 'San Diego', 'CA');
insert into cidade (idCidade, nome, uf) values (774, 'Garden Grove', 'CA');
insert into cidade (idCidade, nome, uf) values (775, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (776, 'Springfield', 'MO');
insert into cidade (idCidade, nome, uf) values (777, 'Trenton', 'NJ');
insert into cidade (idCidade, nome, uf) values (778, 'Scottsdale', 'AZ');
insert into cidade (idCidade, nome, uf) values (779, 'Oklahoma City', 'OK');
insert into cidade (idCidade, nome, uf) values (780, 'Las Cruces', 'NM');
insert into cidade (idCidade, nome, uf) values (781, 'Shawnee Mission', 'KS');
insert into cidade (idCidade, nome, uf) values (782, 'Jacksonville', 'FL');
insert into cidade (idCidade, nome, uf) values (783, 'Atlanta', 'GA');
insert into cidade (idCidade, nome, uf) values (784, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (785, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (786, 'Denver', 'CO');
insert into cidade (idCidade, nome, uf) values (787, 'San Jose', 'CA');
insert into cidade (idCidade, nome, uf) values (788, 'New York City', 'NY');
insert into cidade (idCidade, nome, uf) values (789, 'Lubbock', 'TX');
insert into cidade (idCidade, nome, uf) values (790, 'Pompano Beach', 'FL');
insert into cidade (idCidade, nome, uf) values (791, 'Erie', 'PA');
insert into cidade (idCidade, nome, uf) values (792, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (793, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (794, 'North Las Vegas', 'NV');
insert into cidade (idCidade, nome, uf) values (795, 'Peoria', 'IL');
insert into cidade (idCidade, nome, uf) values (796, 'Grand Rapids', 'MI');
insert into cidade (idCidade, nome, uf) values (797, 'Prescott', 'AZ');
insert into cidade (idCidade, nome, uf) values (798, 'Burbank', 'CA');
insert into cidade (idCidade, nome, uf) values (799, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (800, 'Denver', 'CO');
insert into cidade (idCidade, nome, uf) values (801, 'Fort Lauderdale', 'FL');
insert into cidade (idCidade, nome, uf) values (802, 'Tucson', 'AZ');
insert into cidade (idCidade, nome, uf) values (803, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (804, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (805, 'Evansville', 'IN');
insert into cidade (idCidade, nome, uf) values (806, 'New Bedford', 'MA');
insert into cidade (idCidade, nome, uf) values (807, 'Gastonia', 'NC');
insert into cidade (idCidade, nome, uf) values (808, 'San Jose', 'CA');
insert into cidade (idCidade, nome, uf) values (809, 'Philadelphia', 'PA');
insert into cidade (idCidade, nome, uf) values (810, 'Roanoke', 'VA');
insert into cidade (idCidade, nome, uf) values (811, 'Kansas City', 'KS');
insert into cidade (idCidade, nome, uf) values (812, 'Marietta', 'GA');
insert into cidade (idCidade, nome, uf) values (813, 'Fresno', 'CA');
insert into cidade (idCidade, nome, uf) values (814, 'Dallas', 'TX');
insert into cidade (idCidade, nome, uf) values (815, 'Anaheim', 'CA');
insert into cidade (idCidade, nome, uf) values (816, 'Houston', 'TX');
insert into cidade (idCidade, nome, uf) values (817, 'Jacksonville', 'FL');
insert into cidade (idCidade, nome, uf) values (818, 'Phoenix', 'AZ');
insert into cidade (idCidade, nome, uf) values (819, 'Portsmouth', 'NH');
insert into cidade (idCidade, nome, uf) values (820, 'Atlanta', 'GA');
insert into cidade (idCidade, nome, uf) values (821, 'Berkeley', 'CA');
insert into cidade (idCidade, nome, uf) values (822, 'Phoenix', 'AZ');
insert into cidade (idCidade, nome, uf) values (823, 'Charleston', 'SC');
insert into cidade (idCidade, nome, uf) values (824, 'Nashville', 'TN');
insert into cidade (idCidade, nome, uf) values (825, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (826, 'San Jose', 'CA');
insert into cidade (idCidade, nome, uf) values (827, 'Chicago', 'IL');
insert into cidade (idCidade, nome, uf) values (828, 'Wichita', 'KS');
insert into cidade (idCidade, nome, uf) values (829, 'San Diego', 'CA');
insert into cidade (idCidade, nome, uf) values (830, 'New York City', 'NY');
insert into cidade (idCidade, nome, uf) values (831, 'Birmingham', 'AL');
insert into cidade (idCidade, nome, uf) values (832, 'Evansville', 'IN');
insert into cidade (idCidade, nome, uf) values (833, 'Dallas', 'TX');
insert into cidade (idCidade, nome, uf) values (834, 'Kansas City', 'MO');
insert into cidade (idCidade, nome, uf) values (835, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (836, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (837, 'Spring', 'TX');
insert into cidade (idCidade, nome, uf) values (838, 'Flushing', 'NY');
insert into cidade (idCidade, nome, uf) values (839, 'Worcester', 'MA');
insert into cidade (idCidade, nome, uf) values (840, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (841, 'Muskegon', 'MI');
insert into cidade (idCidade, nome, uf) values (842, 'Dayton', 'OH');
insert into cidade (idCidade, nome, uf) values (843, 'Santa Cruz', 'CA');
insert into cidade (idCidade, nome, uf) values (844, 'Harrisburg', 'PA');
insert into cidade (idCidade, nome, uf) values (845, 'Gaithersburg', 'MD');
insert into cidade (idCidade, nome, uf) values (846, 'Oklahoma City', 'OK');
insert into cidade (idCidade, nome, uf) values (847, 'Miami', 'FL');
insert into cidade (idCidade, nome, uf) values (848, 'Rochester', 'NY');
insert into cidade (idCidade, nome, uf) values (849, 'Worcester', 'MA');
insert into cidade (idCidade, nome, uf) values (850, 'Pittsburgh', 'PA');
insert into cidade (idCidade, nome, uf) values (851, 'Huntington', 'WV');
insert into cidade (idCidade, nome, uf) values (852, 'Washington', 'DC');
insert into cidade (idCidade, nome, uf) values (853, 'Omaha', 'NE');
insert into cidade (idCidade, nome, uf) values (854, 'Rochester', 'NY');
insert into cidade (idCidade, nome, uf) values (855, 'Bradenton', 'FL');
insert into cidade (idCidade, nome, uf) values (856, 'San Diego', 'CA');
insert into cidade (idCidade, nome, uf) values (857, 'San Antonio', 'TX');
insert into cidade (idCidade, nome, uf) values (858, 'Albany', 'NY');
insert into cidade (idCidade, nome, uf) values (859, 'New Orleans', 'LA');
insert into cidade (idCidade, nome, uf) values (860, 'Cedar Rapids', 'IA');
insert into cidade (idCidade, nome, uf) values (861, 'Charlotte', 'NC');
insert into cidade (idCidade, nome, uf) values (862, 'Philadelphia', 'PA');
insert into cidade (idCidade, nome, uf) values (863, 'Independence', 'MO');
insert into cidade (idCidade, nome, uf) values (864, 'Independence', 'MO');
insert into cidade (idCidade, nome, uf) values (865, 'Evansville', 'IN');
insert into cidade (idCidade, nome, uf) values (866, 'Vienna', 'VA');
insert into cidade (idCidade, nome, uf) values (867, 'Youngstown', 'OH');
insert into cidade (idCidade, nome, uf) values (868, 'Portland', 'OR');
insert into cidade (idCidade, nome, uf) values (869, 'Lynchburg', 'VA');
insert into cidade (idCidade, nome, uf) values (870, 'Saint Cloud', 'MN');
insert into cidade (idCidade, nome, uf) values (871, 'Fullerton', 'CA');
insert into cidade (idCidade, nome, uf) values (872, 'Aurora', 'IL');
insert into cidade (idCidade, nome, uf) values (873, 'San Jose', 'CA');
insert into cidade (idCidade, nome, uf) values (874, 'Beaufort', 'SC');
insert into cidade (idCidade, nome, uf) values (875, 'Stamford', 'CT');
insert into cidade (idCidade, nome, uf) values (876, 'Atlanta', 'GA');
insert into cidade (idCidade, nome, uf) values (877, 'Saint Petersburg', 'FL');
insert into cidade (idCidade, nome, uf) values (878, 'Duluth', 'GA');
insert into cidade (idCidade, nome, uf) values (879, 'Pasadena', 'TX');
insert into cidade (idCidade, nome, uf) values (880, 'Springfield', 'VA');
insert into cidade (idCidade, nome, uf) values (881, 'Schenectady', 'NY');
insert into cidade (idCidade, nome, uf) values (882, 'Stamford', 'CT');
insert into cidade (idCidade, nome, uf) values (883, 'Salt Lake City', 'UT');
insert into cidade (idCidade, nome, uf) values (884, 'Houston', 'TX');
insert into cidade (idCidade, nome, uf) values (885, 'Anaheim', 'CA');
insert into cidade (idCidade, nome, uf) values (886, 'Shreveport', 'LA');
insert into cidade (idCidade, nome, uf) values (887, 'Decatur', 'IL');
insert into cidade (idCidade, nome, uf) values (888, 'Fort Wayne', 'IN');
insert into cidade (idCidade, nome, uf) values (889, 'Decatur', 'IL');
insert into cidade (idCidade, nome, uf) values (890, 'Miami', 'FL');
insert into cidade (idCidade, nome, uf) values (891, 'Gainesville', 'FL');
insert into cidade (idCidade, nome, uf) values (892, 'New York City', 'NY');
insert into cidade (idCidade, nome, uf) values (893, 'Minneapolis', 'MN');
insert into cidade (idCidade, nome, uf) values (894, 'Corpus Christi', 'TX');
insert into cidade (idCidade, nome, uf) values (895, 'Peoria', 'IL');
insert into cidade (idCidade, nome, uf) values (896, 'Atlanta', 'GA');
insert into cidade (idCidade, nome, uf) values (897, 'Chicago', 'IL');
insert into cidade (idCidade, nome, uf) values (898, 'San Diego', 'CA');
insert into cidade (idCidade, nome, uf) values (899, 'Virginia Beach', 'VA');
insert into cidade (idCidade, nome, uf) values (900, 'Fort Lauderdale', 'FL');
insert into cidade (idCidade, nome, uf) values (901, 'Pensacola', 'FL');
insert into cidade (idCidade, nome, uf) values (902, 'Detroit', 'MI');
insert into cidade (idCidade, nome, uf) values (903, 'Richmond', 'VA');
insert into cidade (idCidade, nome, uf) values (904, 'Chula Vista', 'CA');
insert into cidade (idCidade, nome, uf) values (905, 'Brea', 'CA');
insert into cidade (idCidade, nome, uf) values (906, 'Columbus', 'OH');
insert into cidade (idCidade, nome, uf) values (907, 'Vienna', 'VA');
insert into cidade (idCidade, nome, uf) values (908, 'Columbus', 'OH');
insert into cidade (idCidade, nome, uf) values (909, 'Ventura', 'CA');
insert into cidade (idCidade, nome, uf) values (910, 'Fresno', 'CA');
insert into cidade (idCidade, nome, uf) values (911, 'Stamford', 'CT');
insert into cidade (idCidade, nome, uf) values (912, 'Lakeland', 'FL');
insert into cidade (idCidade, nome, uf) values (913, 'Fort Lauderdale', 'FL');
insert into cidade (idCidade, nome, uf) values (914, 'Chicago', 'IL');
insert into cidade (idCidade, nome, uf) values (915, 'Wichita Falls', 'TX');
insert into cidade (idCidade, nome, uf) values (916, 'San Diego', 'CA');
insert into cidade (idCidade, nome, uf) values (917, 'San Francisco', 'CA');
insert into cidade (idCidade, nome, uf) values (918, 'Seattle', 'WA');
insert into cidade (idCidade, nome, uf) values (919, 'Texarkana', 'TX');
insert into cidade (idCidade, nome, uf) values (920, 'Warren', 'OH');
insert into cidade (idCidade, nome, uf) values (921, 'New Orleans', 'LA');
insert into cidade (idCidade, nome, uf) values (922, 'Austin', 'TX');
insert into cidade (idCidade, nome, uf) values (923, 'Oakland', 'CA');
insert into cidade (idCidade, nome, uf) values (924, 'Salt Lake City', 'UT');
insert into cidade (idCidade, nome, uf) values (925, 'Reading', 'PA');
insert into cidade (idCidade, nome, uf) values (926, 'Lansing', 'MI');
insert into cidade (idCidade, nome, uf) values (927, 'Jacksonville', 'FL');
insert into cidade (idCidade, nome, uf) values (928, 'Riverside', 'CA');
insert into cidade (idCidade, nome, uf) values (929, 'San Antonio', 'TX');
insert into cidade (idCidade, nome, uf) values (930, 'Sioux City', 'IA');
insert into cidade (idCidade, nome, uf) values (931, 'Fort Lauderdale', 'FL');
insert into cidade (idCidade, nome, uf) values (932, 'Davenport', 'IA');
insert into cidade (idCidade, nome, uf) values (933, 'Reno', 'NV');
insert into cidade (idCidade, nome, uf) values (934, 'Seattle', 'WA');
insert into cidade (idCidade, nome, uf) values (935, 'Huntsville', 'AL');
insert into cidade (idCidade, nome, uf) values (936, 'Long Beach', 'CA');
insert into cidade (idCidade, nome, uf) values (937, 'Rochester', 'NY');
insert into cidade (idCidade, nome, uf) values (938, 'Texarkana', 'TX');
insert into cidade (idCidade, nome, uf) values (939, 'Jackson', 'MS');
insert into cidade (idCidade, nome, uf) values (940, 'Schaumburg', 'IL');
insert into cidade (idCidade, nome, uf) values (941, 'Greeley', 'CO');
insert into cidade (idCidade, nome, uf) values (942, 'Tucson', 'AZ');
insert into cidade (idCidade, nome, uf) values (943, 'Portsmouth', 'NH');
insert into cidade (idCidade, nome, uf) values (944, 'Fort Worth', 'TX');
insert into cidade (idCidade, nome, uf) values (945, 'Lexington', 'KY');
insert into cidade (idCidade, nome, uf) values (946, 'Gilbert', 'AZ');
insert into cidade (idCidade, nome, uf) values (947, 'Staten Island', 'NY');
insert into cidade (idCidade, nome, uf) values (948, 'Sioux City', 'IA');
insert into cidade (idCidade, nome, uf) values (949, 'Beaumont', 'TX');
insert into cidade (idCidade, nome, uf) values (950, 'Bakersfield', 'CA');
insert into cidade (idCidade, nome, uf) values (951, 'Indianapolis', 'IN');
insert into cidade (idCidade, nome, uf) values (952, 'Omaha', 'NE');
insert into cidade (idCidade, nome, uf) values (953, 'Tyler', 'TX');
insert into cidade (idCidade, nome, uf) values (954, 'Rockford', 'IL');
insert into cidade (idCidade, nome, uf) values (955, 'Pittsburgh', 'PA');
insert into cidade (idCidade, nome, uf) values (956, 'Green Bay', 'WI');
insert into cidade (idCidade, nome, uf) values (957, 'Fort Worth', 'TX');
insert into cidade (idCidade, nome, uf) values (958, 'Miami', 'FL');
insert into cidade (idCidade, nome, uf) values (959, 'Saint Louis', 'MO');
insert into cidade (idCidade, nome, uf) values (960, 'El Paso', 'TX');
insert into cidade (idCidade, nome, uf) values (961, 'Albany', 'NY');
insert into cidade (idCidade, nome, uf) values (962, 'Pinellas Park', 'FL');
insert into cidade (idCidade, nome, uf) values (963, 'Salt Lake City', 'UT');
insert into cidade (idCidade, nome, uf) values (964, 'San Antonio', 'TX');
insert into cidade (idCidade, nome, uf) values (965, 'Southfield', 'MI');
insert into cidade (idCidade, nome, uf) values (966, 'Baton Rouge', 'LA');
insert into cidade (idCidade, nome, uf) values (967, 'Detroit', 'MI');
insert into cidade (idCidade, nome, uf) values (968, 'Chicago', 'IL');
insert into cidade (idCidade, nome, uf) values (969, 'Charleston', 'SC');
insert into cidade (idCidade, nome, uf) values (970, 'Springfield', 'IL');
insert into cidade (idCidade, nome, uf) values (971, 'Waco', 'TX');
insert into cidade (idCidade, nome, uf) values (972, 'Woburn', 'MA');
insert into cidade (idCidade, nome, uf) values (973, 'San Jose', 'CA');
insert into cidade (idCidade, nome, uf) values (974, 'Atlanta', 'GA');
insert into cidade (idCidade, nome, uf) values (975, 'Lexington', 'KY');
insert into cidade (idCidade, nome, uf) values (976, 'Jamaica', 'NY');
insert into cidade (idCidade, nome, uf) values (977, 'Lansing', 'MI');
insert into cidade (idCidade, nome, uf) values (978, 'New York City', 'NY');
insert into cidade (idCidade, nome, uf) values (979, 'Tucson', 'AZ');
insert into cidade (idCidade, nome, uf) values (980, 'Roanoke', 'VA');
insert into cidade (idCidade, nome, uf) values (981, 'Conroe', 'TX');
insert into cidade (idCidade, nome, uf) values (982, 'Tucson', 'AZ');
insert into cidade (idCidade, nome, uf) values (983, 'New York City', 'NY');
insert into cidade (idCidade, nome, uf) values (984, 'Harrisburg', 'PA');
insert into cidade (idCidade, nome, uf) values (985, 'Des Moines', 'IA');
insert into cidade (idCidade, nome, uf) values (986, 'Salt Lake City', 'UT');
insert into cidade (idCidade, nome, uf) values (987, 'Tacoma', 'WA');
insert into cidade (idCidade, nome, uf) values (988, 'San Jose', 'CA');
insert into cidade (idCidade, nome, uf) values (989, 'Reno', 'NV');
insert into cidade (idCidade, nome, uf) values (990, 'Saint Petersburg', 'FL');
insert into cidade (idCidade, nome, uf) values (991, 'Atlanta', 'GA');
insert into cidade (idCidade, nome, uf) values (992, 'Indianapolis', 'IN');
insert into cidade (idCidade, nome, uf) values (993, 'Macon', 'GA');
insert into cidade (idCidade, nome, uf) values (994, 'Conroe', 'TX');
insert into cidade (idCidade, nome, uf) values (995, 'Phoenix', 'AZ');
insert into cidade (idCidade, nome, uf) values (996, 'Pittsburgh', 'PA');
insert into cidade (idCidade, nome, uf) values (997, 'Carlsbad', 'CA');
insert into cidade (idCidade, nome, uf) values (998, 'Fort Pierce', 'FL');
insert into cidade (idCidade, nome, uf) values (999, 'Portsmouth', 'NH');
insert into cidade (idCidade, nome, uf) values (1000, 'Chicago', 'IL');
